### ISSUE TITLE
Wondering whether this is immediate-mode or retained UI lib

### ISSUE THREAD

**Issue by dumblob** [kettle11/kui#1]
What's the goal for this UI lib regarding architecture? Will this be [immediate mode UI lib](https://en.wikipedia.org/wiki/Immediate_mode_GUI ) (e.g. https://github.com/Immediate-Mode-UI/ ) or rather [retained mode UI lib](https://en.wikipedia.org/wiki/Retained_mode )?

**Comment by kettle11** [comment]
This crate is very work in progress (I'm surprised you even stumbled across it!) but it's a hybrid of immediate and retained.

The UI is created with an immediate mode style API. A button would be declared like the following:

```rust
if button(&toolbar, id!(), "Add Cube") {
    println!("Added a cube");
}
```

But an ID preserves the button widget's animation state across frames (like a retained library). I went with this approach because I like the speed of developer iteration possible with immediate mode UI's, but I'd also like nice animations and managing that state in an immediate way was a bit annoying.

While this library has a few really nice things going for it it still needs a bunch of work before I'm content with the architecture.

**Comment by dumblob** [comment]
I see, thanks.

Btw. if you'd wanted some more visibility for this project at some point (especially among potential contributors), I'd be more than happy to add this lib to https://github.com/Immediate-Mode-UI/ organization (it's not an organization per se - there are no rules and no duties - it's just a list of projects considering themself as some sort of immediate mode UI library/app/algorithm).
